export const ALL_PRODUCTS = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    category: "Electronics",
    price: 99.99,
    rating: 120,
    image: "p1.jpg",
  },
  {
    id: 2,
    name: "Smart Watch Series 5",
    category: "Electronics",
    price: 299.99,
    rating: 85,
    image: "p2.jpg",
  },
  {
    id: 3,
    name: "Comfortable Cotton T-Shirt",
    category: "Clothing",
    price: 24.99,
    rating: 200,
    image: "p3.jpg",
  },
  {
    id: 4,
    name: "Ergonomic Office Chair",
    category: "Furniture",
    price: 199.99,
    rating: 65,
    image: "p4.jpg",
  },
  {
    id: 5,
    name: "Stainless Steel Water Bottle",
    category: "Home",
    price: 34.99,
    rating: 150,
    image: "p5.jpg",
  },
  {
    id: 6,
    name: "Professional Camera Lens",
    category: "Electronics",
    price: 599.99,
    rating: 45,
    image: "p6.jpg",
  },
  {
    id: 7,
    name: "Running Shoes",
    category: "Clothing",
    price: 129.99,
    rating: 180,
    image: "p7.jpg",
  },
  {
    id: 8,
    name: "Modern Coffee Table",
    category: "Furniture",
    price: 149.99,
    rating: 90,
    image: "p8.jpg",
  },
  {
    id: 9,
    name: "Aromatherapy Essential Oil Diffuser",
    category: "Home",
    price: 49.99,
    rating: 110,
    image: "p9.jpg",
  },
  {
    id: 10,
    name: "Wireless Gaming Mouse",
    category: "Electronics",
    price: 79.99,
    rating: 95,
    image: "p10.jpg",
  },
  {
    id: 11,
    name: "Yoga Mat",
    category: "Sports",
    price: 39.99,
    rating: 130,
    image: "p11.jpg",
  },
  {
    id: 12,
    name: "Leather Wallet",
    category: "Accessories",
    price: 29.99,
    rating: 75,
    image: "p12.jpg",
  },
  {
    id: 13,
    name: "4K Ultra HD Monitor",
    category: "Electronics",
    price: 349.99,
    rating: 88,
    image: "p13.jpg",
  },
  {
    id: 14,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 149.99,
    rating: 142,
    image: "p14.jpg",
  },
  {
    id: 15,
    name: "Portable Power Bank",
    category: "Electronics",
    price: 49.99,
    rating: 203,
    image: "p15.jpg",
  },
  {
    id: 16,
    name: "Wireless Earbuds",
    category: "Electronics",
    price: 89.99,
    rating: 167,
    image: "p16.jpg",
  },
  {
    id: 17,
    name: "Smart Home Hub",
    category: "Electronics",
    price: 129.99,
    rating: 134,
    image: "p17.jpg",
  },
  {
    id: 18,
    name: "Fitness Tracker",
    category: "Electronics",
    price: 79.99,
    rating: 189,
    image: "p18.jpg",
  },
  {
    id: 19,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 69.99,
    rating: 156,
    image: "p19.jpg",
  },
  {
    id: 20,
    name: "Gaming Headset",
    category: "Electronics",
    price: 119.99,
    rating: 98,
    image: "p20.jpg",
  },
  {
    id: 21,
    name: "Digital Camera",
    category: "Electronics",
    price: 449.99,
    rating: 112,
    image: "p21.jpg",
  },
  {
    id: 22,
    name: "Tablet Stand",
    category: "Accessories",
    price: 29.99,
    rating: 87,
    image: "p22.jpg",
  },
  {
    id: 23,
    name: "Desk Lamp",
    category: "Home",
    price: 39.99,
    rating: 145,
    image: "p23.jpg",
  },
  {
    id: 24,
    name: "Backpack",
    category: "Accessories",
    price: 59.99,
    rating: 178,
    image: "p24.jpg",
  },
  {
    id: 25,
    name: "Coffee Maker",
    category: "Home",
    price: 89.99,
    rating: 203,
    image: "p25.jpg",
  },
  {
    id: 26,
    name: "Dumbbells Set",
    category: "Sports",
    price: 79.99,
    rating: 134,
    image: "p26.jpg",
  },
  {
    id: 27,
    name: "Sunglasses",
    category: "Accessories",
    price: 49.99,
    rating: 156,
    image: "p27.jpg",
  },
  {
    id: 28,
    name: "Bookshelf",
    category: "Furniture",
    price: 129.99,
    rating: 92,
    image: "p28.jpg",
  },
  {
    id: 29,
    name: "Wireless Charger",
    category: "Electronics",
    price: 24.99,
    rating: 189,
    image: "p29.jpg",
  },
  {
    id: 30,
    name: "Throw Blanket",
    category: "Home",
    price: 34.99,
    rating: 167,
    image: "p30.jpg",
  },
  {
    id: 31,
    name: "Resistance Bands Set",
    category: "Sports",
    price: 19.99,
    rating: 145,
    image: "p31.jpg",
  },
  {
    id: 32,
    name: "Wall Clock",
    category: "Home",
    price: 39.99,
    rating: 98,
    image: "p32.jpg",
  },
  {
    id: 33,
    name: "Phone Case",
    category: "Accessories",
    price: 14.99,
    rating: 234,
    image: "p33.jpg",
  },
  {
    id: 34,
    name: "Floor Lamp",
    category: "Home",
    price: 79.99,
    rating: 87,
    image: "p34.jpg",
  },
  {
    id: 35,
    name: "Protein Powder",
    category: "Sports",
    price: 49.99,
    rating: 312,
    image: "p35.jpg",
  },
  {
    id: 36,
    name: "Desk Organizer",
    category: "Home",
    price: 24.99,
    rating: 145,
    image: "p36.jpg",
  },
  {
    id: 37,
    name: "Wireless Router",
    category: "Electronics",
    price: 99.99,
    rating: 178,
    image: "p37.jpg",
  },
  {
    id: 38,
    name: "Pillow Set",
    category: "Home",
    price: 39.99,
    rating: 156,
    image: "p38.jpg",
  },
  {
    id: 39,
    name: "Tennis Racket",
    category: "Sports",
    price: 89.99,
    rating: 89,
    image: "p39.jpg",
  },
  {
    id: 40,
    name: "Candles Set",
    category: "Home",
    price: 29.99,
    rating: 203,
    image: "p40.jpg",
  },
  {
    id: 41,
    name: "External Hard Drive",
    category: "Electronics",
    price: 79.99,
    rating: 167,
    image: "p41.jpg",
  },
  {
    id: 42,
    name: "Yoga Blocks",
    category: "Sports",
    price: 19.99,
    rating: 134,
    image: "p42.jpg",
  },
  {
    id: 43,
    name: "Picture Frame",
    category: "Home",
    price: 24.99,
    rating: 98,
    image: "p43.jpg",
  },
  {
    id: 44,
    name: "Bike Helmet",
    category: "Sports",
    price: 49.99,
    rating: 145,
    image: "p44.jpg",
  },
  {
    id: 45,
    name: "Air Purifier",
    category: "Home",
    price: 149.99,
    rating: 187,
    image: "p45.jpg",
  },
  {
    id: 46,
    name: "Webcam",
    category: "Electronics",
    price: 59.99,
    rating: 156,
    image: "p46.jpg",
  },
  {
    id: 47,
    name: "Plant Pot",
    category: "Home",
    price: 19.99,
    rating: 123,
    image: "p47.jpg",
  },
  {
    id: 48,
    name: "Swim Goggles",
    category: "Sports",
    price: 14.99,
    rating: 178,
    image: "p48.jpg",
  },
  {
    id: 49,
    name: "Notebook Set",
    category: "Accessories",
    price: 12.99,
    rating: 145,
    image: "p49.jpg",
  },
  {
    id: 50,
    name: "Wall Art",
    category: "Home",
    price: 39.99,
    rating: 87,
    image: "p50.jpg",
  },
];
